import type { Metadata } from "next";

import "@/app/globals.css";

import { Toaster } from "react-hot-toast";
import ReactQueryClientProvider from "@/provider/ReactQueryClientProvider";
import { Box } from "@mui/material";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReactQueryClientProvider>
      <Toaster />
      <Box className="flex justify-center items-center h-screen">
        {children}
      </Box>
    </ReactQueryClientProvider>
  );
}
