import type { Metadata } from "next";
import "@/app/globals.css";

import { Toaster } from "react-hot-toast";
import { Box } from "@mui/material";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Box className="flex justify-center items-center h-screen">
      <Toaster />
      {children}
    </Box>
  );
}
