import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/app/globals.css";

import { Toaster } from "react-hot-toast";
import ReactQueryClientProvider from "@/provider/ReactQueryClientProvider";
import NavBar from "../../components/basic/NavBar";
import Footer from "@/components/basic/Footer";
import AuthGuard from "@/components/guards/AuthGuard";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col`}
      >
        <ReactQueryClientProvider>
          <Toaster />
          <AuthGuard>
            <NavBar />
            {children}
            <Footer />
          </AuthGuard>
        </ReactQueryClientProvider>
      </body>
    </html>
  );
}
